# Generated by Django 3.2.16 on 2023-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(help_text='用户注册', max_length=24, verbose_name='用户注册'),
        ),
    ]
