# Generated by Django 3.2.16 on 2023-01-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_test01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(verbose_name='出版社主键')),
                ('name', models.CharField(max_length=50, verbose_name='出版社')),
                ('addr', models.CharField(max_length=80, null=True, verbose_name='地址')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='public',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='定价'),
        ),
        migrations.AddField(
            model_name='book',
            name='public_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.pub'),
        ),
    ]
